### ISSUE TITLE
Dart code file size

### ISSUE THREAD

**Issue by restacksyj** [VB10/manhang#4]
Hey , I just wanted to know how did you measure your dart code file size . When I measured it using this command 
find . -name "*.dart" | xargs cat | wc -c 
the output is 8862 bytes which is above the limit of 5032 bytes of flutter create . So I just wanted to clarify it with you .

**Comment by VB10** [comment]
hello, I see this problem and fix remove the home screen and some components. Now size 5031 😄
Thanks a lot.
Best regards  @TheDeveloperYJ
